//
// Module mopshub_readout_lib.elink_transmitter.struct
//
// Created:
//          by - dcs.dcs (localhost)
//          at - 16:12:23 05/03/24
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module elink_transmitter( 
   // Port Declarations
   input   wire           fifo_wr_en, 
   input   wire           clk, 
   input   wire    [9:0]  fifo_din, 
   input   wire           fifo_flush, 
   output  wire    [1:0]  data_2bit_out,  //  @ 40MHz
   output  wire           efifo_empty, 
   output  wire           efifo_full, 
   input   wire           rst, 
   input   wire    [7:0]  Kchar_comma, 
   input   wire           clk_elink
);

// Local declarations
// Internal signal declarations
// Internal Declarations
// Internal Declarations


// Local declarations

// Internal signal declarations
wire  [9:0] data_10bit_in_fifo;    // 10-bit data in
wire        data_rdy_10bit_fifo;
wire        get_data_trig;
wire        wr_en_comma;


// Instances 
elink_proc_out_enc8b10b elink_proc_out_enc8b10b0( 
   .clk           (clk_elink), 
   .data_10bit_in (data_10bit_in_fifo), 
   .data_out_rdy  (data_rdy_10bit_fifo), 
   .rst           (rst), 
   .get_data_trig (get_data_trig), 
   .data_2bit_out (data_2bit_out)
); 

fifo_core_wrapper fifo_core_wrap_tx( 
   .Kchar_comma     (Kchar_comma), 
   .din_fifo        (fifo_din), 
   .flush_fifo      (fifo_flush), 
   .rclk            (clk_elink), 
   .rd_en           (get_data_trig), 
   .rst             (rst), 
   .wclk            (clk), 
   .wr_en           (fifo_wr_en), 
   .wr_en_comma     (wr_en_comma), 
   .dout_fifo       (data_10bit_in_fifo), 
   .full_fifo       (efifo_full), 
   .rdy_fifo        (data_rdy_10bit_fifo), 
   .read_fifo_empty (efifo_empty)
); 

// HDL Embedded Text Block 11 FIFO_write2
assign wr_en_comma   =1'b1;




















































































































































endmodule // elink_transmitter
// FIFO_to_Elink
