//
// Module mopshub_readout_lib.mopshub_readout.struct
//
// Created:
//          by - dcs.dcs (localhost)
//          at - 16:41:17 05/03/24
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module mopshub_readout( 
   // Port Declarations
   // Port Declarations
   input   wire           clk125, 
   input   wire           clk_40, 
   input   wire           clk_rx, 
   input   wire           clk_tx, 
   input   wire           dbg_elink, 
   input   wire    [3:0]  dip_sw, 
   input   wire           gmii_rx_dv, 
   input   wire           gmii_rx_er, 
   input   wire    [7:0]  gmii_rxd, 
   input   wire           mmcm_locked, 
   input   wire           reset, 
   input   wire           resetdone, 
   input   wire           rx_elink_n, 
   input   wire           rx_elink_p, 
   output  wire           clk_ipb, 
   output  wire    [4:0]  configuration_vector, 
   output  wire           gmii_tx_en, 
   output  wire           gmii_tx_er, 
   output  wire    [7:0]  gmii_txd, 
   output  wire           irq_can_rec, 
   output  wire           irq_can_tra, 
   output  wire           irq_elink_dbg, 
   output  wire           irq_elink_rec, 
   output  wire           led, 
   output  wire           rst_eth, 
   output  wire           rx_data_rdy, 
   output  wire           sfp_enable, 
   output  wire           tx_data_rdy, 
   output  wire           tx_elink_n, 
   output  wire           tx_elink_p, 
   input   wire           locked, 
   output  wire           clk_out_p, 
   output  wire           clk_out_n, 
   output  wire    [7:0]  counter_rst_mopshub, 
   output  wire    [7:0]  counter_disp_err, 
   output  wire    [7:0]  counter_code_err, 
   input   wire           clk_elink, 
   output  wire           irq_elink_tra, 
   input   wire           sysclk_n, 
   input   wire           sysclk_p, 
   output  wire    [7:0]  dec10b_in_dbg_uart, 
   input   wire           clk_uart, 
   output  wire           out_tx_serial, 
   input   wire           in_rx_serial, 
   input   wire           clk_m, 
   input   wire    [3:0]  mopshub_id, 
   output  wire    [7:0]  counter_dec10b_in_rdy
);

// Internal Declarations


// Local declarations

// Internal signal declarations
// Internal Declarations


// Local declarations

// Internal signal declarations
wire         irq_can_rec_in;
wire         irq_can_tra_in;
wire         irq_elink_rec_in;
wire         irq_elink_tra_in;
wire         rx_data_rdy_in;
wire         tx_data_rdy_in;
wire  [75:0] data_rec_elink_dbg;
wire  [75:0] data_rec_uplink;
wire  [75:0] data_tra_downlink;
wire         enable_cnt               = 1'b1;   // pfull from Tx FIFO
wire         eth_led;
wire         irq_elink_dbg_in_active;
wire         rst;
wire  [1:0]  rx_elink2bit;
wire         rx_fifo_full_rdy;
wire         start_write_elink_dbg;
wire         tx_fifo_full_rdy;
wire         word10b_rdy;
wire  [4:0]  n_buses;
wire         debug_mode;
wire         dbg_spi;
wire         miso_m;
wire         miso_c;
wire         irq_elink_eth;
wire         buffer_eth_en;
wire  [1:0]  tx_elink2bit;
wire  [11:0] xadc_rec_in;
wire  [7:0]  statedeb_can             = 8'h0;
wire  [7:0]  statedeb_main            = 8'h3;
wire  [7:0]  statedeb_osc_trim        = 8'h2;
wire         start_read_eth_fifo;
wire  [7:0]  Kchar_comma;
wire         rx_fifo_full_in;
wire         tx_efifo_full_in;
wire         dec10b_in_rdy_dbg;
wire         end_write_elink;
wire  [9:0]  COMMAp;
wire  [9:0]  COMMAn;
wire  [7:0]  Kchar_eop;
wire         buffer_en;
reg   [31:0] time_limit;
wire         timeoutrst;
wire         end_read_elink;
reg          abort;
wire  [9:0]  dec10b_in_dbg;
reg          fifo_flush;                        // Upon receiving a reset message on the CANbus. FSM goes into a known state
wire  [7:0]  Kchar_sop;
wire         endwait_all;                       // Upon receiving a reset message on the CANbus. FSM goes into a known state
wire  [7:0]  statedb_can_mux          = 8'h1;
wire         end_write_elink_dbg;
wire         end_elink_proc           = 1'b1;
wire         code_err;
wire         disp_err;
wire         rst_id_rec;
wire  [7:0]  statedeb_elink_rec;
wire  [7:0]  statedeb_elink_tra;
wire  [7:0]  data13                   = 8'h6;
wire  [7:0]  data14                   = 8'h7;
wire         dec10b_in_rdy_sop;
wire         enable_timeout2          = 1'b0;
wire         enable_timeout0          = 1'b0;
wire  [7:0]  statedeb_spi             = 8'h5;   // debug signal from SPI SM
wire  [7:0]  counter_enc10b_out_rdy   = 8'h4;
wire         start_read_elink         = 1'b1;
wire         enable_timeout1          = 1'b0;


// Instances 
counter_enable counter_enable_code_err( 
   .rst          (rst), 
   .clk          (clk_elink), 
   .request_trig (code_err), 
   .send_count   (counter_code_err)
); 

counter_enable counter_enable_dec10b_in_rdy( 
   .rst          (rst), 
   .clk          (clk_elink), 
   .request_trig (dec10b_in_rdy_sop), 
   .send_count   (counter_dec10b_in_rdy)
); 

counter_enable counter_enable_disp_err( 
   .rst          (rst), 
   .clk          (clk_elink), 
   .request_trig (disp_err), 
   .send_count   (counter_disp_err)
); 

counter_enable counter_enable_rst_id_rec( 
   .rst          (rst), 
   .clk          (clk_40), 
   .request_trig (rst_id_rec), 
   .send_count   (counter_rst_mopshub)
); 

debug_uart_core #(100) debug_uart_core0( 
   .clk_40                 (clk_40), 
   .clk_uart               (clk_uart), 
   .counter_code_err       (counter_code_err), 
   .counter_dec10b_in_rdy  (counter_dec10b_in_rdy), 
   .counter_disp_err       (counter_disp_err), 
   .counter_enc10b_out_rdy (counter_enc10b_out_rdy), 
   .counter_rst_mopshub    (counter_rst_mopshub), 
   .data13                 (data13), 
   .data14                 (data14), 
   .dec10b_in_dbg          (dec10b_in_dbg_uart), 
   .in_rx_serial           (in_rx_serial), 
   .rst                    (rst), 
   .statedb_can_mux        (statedb_can_mux), 
   .statedeb_can           (statedeb_can), 
   .statedeb_elink_rec     (statedeb_elink_rec), 
   .statedeb_elink_tra     (statedeb_elink_tra), 
   .statedeb_main          (statedeb_main), 
   .statedeb_osc_trim      (statedeb_osc_trim), 
   .statedeb_spi           (statedeb_spi), 
   .out_tx_serial          (out_tx_serial)
); 

elink_core elink_core0( 
   .clk                   (clk_40), 
   .rst                   (rst), 
   .rx_fifo_full          (rx_fifo_full_in), 
   .tx_efifo_full         (tx_efifo_full_in), 
   .irq_elink_rec         (irq_elink_rec_in), 
   .irq_elink_tra         (irq_elink_tra_in), 
   .end_write_elink       (end_write_elink), 
   .start_read_elink      (start_read_elink), 
   .end_read_elink        (end_read_elink), 
   .data_2bit_in          (rx_elink2bit), 
   .data_2bit_out         (tx_elink2bit), 
   .fifo_flush            (fifo_flush), 
   .tx_data_rdy           (tx_data_rdy_in), 
   .rx_data_rdy           (rx_data_rdy_in), 
   .data_tra_out          (data_tra_downlink), 
   .buffer_tra_en         (buffer_en), 
   .timeoutrst            (timeoutrst), 
   .abort                 (abort), 
   .statedeb_elink_tra    (statedeb_elink_tra), 
   .statedeb_elink_rec    (statedeb_elink_rec), 
   .word10b_rdy           (word10b_rdy), 
   .start_write_elink_dbg (start_write_elink_dbg), 
   .data_rec_dbg_in       (data_rec_elink_dbg), 
   .end_write_elink_dbg   (end_write_elink_dbg), 
   .irq_elink_eth         (irq_elink_eth), 
   .buffer_eth_en         (buffer_eth_en), 
   .dec10b_in_dbg         (dec10b_in_dbg), 
   .dec10b_in_rdy_dbg     (dec10b_in_rdy_dbg), 
   .Kchar_comma           (Kchar_comma), 
   .Kchar_eop             (Kchar_eop), 
   .Kchar_sop             (Kchar_sop), 
   .COMMAn                (COMMAn), 
   .COMMAp                (COMMAp), 
   .start_read_eth_fifo   (start_read_eth_fifo), 
   .end_elink_proc        (end_elink_proc), 
   .clk_elink             (clk_elink), 
   .endwait               (endwait_all), 
   .code_err              (code_err), 
   .disp_err              (disp_err), 
   .rst_id_rec            (rst_id_rec), 
   .mopshub_id            (mopshub_id)
); 

ethernet_core ethernet_core0( 
   .clk125                (clk125), 
   .data_rec_uplink       (data_rec_uplink), 
   .data_tra_downlink     (data_tra_downlink), 
   .dip_sw                (dip_sw), 
   .gmii_rx_dv            (gmii_rx_dv), 
   .gmii_rx_er            (gmii_rx_er), 
   .gmii_rxd              (gmii_rxd), 
   .mmcm_locked           (mmcm_locked), 
   .resetdone             (resetdone), 
   .clk_ipb               (clk_ipb), 
   .configuration_vector  (configuration_vector), 
   .data_rec_elink_dbg    (data_rec_elink_dbg), 
   .gmii_tx_en            (gmii_tx_en), 
   .gmii_tx_er            (gmii_tx_er), 
   .gmii_txd              (gmii_txd), 
   .led                   (eth_led), 
   .rst_eth               (rst_eth), 
   .sfp_enable            (sfp_enable), 
   .start_write_elink_dbg (start_write_elink_dbg), 
   .clk                   (clk_40), 
   .rst                   (rst), 
   .irq_elink_dbg_in      (irq_elink_eth), 
   .start_read_eth_fifo   (start_read_eth_fifo), 
   .sysclk_n              (sysclk_n), 
   .sysclk_p              (sysclk_p)
); 

ip_output_diff_clk_mopshub_debug ip_output_diff_clk_mopshub_debug0( 
   .clk_in    (clk_m), 
   .locked    (locked), 
   .clk_out_p (clk_out_p), 
   .clk_out_n (clk_out_n)
); 

ip_select_io_ddr_wrapper ip_select_io_ddr_wrapper0( 
   .clk_rx       (clk_rx), 
   .clk_tx       (clk_tx), 
   .reset        (reset), 
   .rx_elink_n   (rx_elink_n), 
   .rx_elink_p   (rx_elink_p), 
   .rx_elink2bit (rx_elink2bit), 
   .tx_elink2bit (tx_elink2bit), 
   .tx_elink_n   (tx_elink_n), 
   .tx_elink_p   (tx_elink_p)
); 

timeout_rst_watchdog timout_rst_watchdog0( 
   .clk             (clk_40), 
   .enable_timeout0 (enable_timeout0), 
   .enable_timeout1 (enable_timeout1), 
   .enable_timeout2 (enable_timeout2), 
   .time_limit      (time_limit), 
   .rst             (rst), 
   .rst_timeout     (timeoutrst)
); 

top_led_enable_sm top_led_enable_sm5( 
   .clk_in     (clk_40), 
   .enable_cnt (enable_cnt), 
   .rst        (rst), 
   .led        (led)
); 

top_led_for_synth top_led_for_synth0( 
   .clk                  (clk_40), 
   .irq_can_rec_in       (irq_can_rec_in), 
   .irq_can_tra_in       (irq_can_tra_in), 
   .irq_elink_dbg_in     (irq_elink_dbg_in_active), 
   .irq_elink_rec_in     (end_write_elink_dbg), 
   .irq_elink_tra_in     (irq_elink_tra_in), 
   .rst                  (rst), 
   .rx_data_rdy_in       (word10b_rdy), 
   .rx_fifo_full_rdy_in  (rx_fifo_full_in), 
   .tx_data_rdy_in       (tx_data_rdy_in), 
   .tx_fifo_full_rdy_in  (tx_efifo_full_in), 
   .irq_can_rec_out      (irq_can_rec), 
   .irq_can_tra_out      (irq_can_tra), 
   .irq_elink_dbg_out    (irq_elink_dbg), 
   .irq_elink_rec_out    (irq_elink_rec), 
   .irq_elink_tra_out    (irq_elink_tra), 
   .rx_data_rdy_out      (rx_data_rdy), 
   .rx_fifo_full_rdy_out (rx_fifo_full_rdy), 
   .tx_data_rdy_out      (tx_data_rdy), 
   .tx_fifo_full_rdy_out (tx_fifo_full_rdy)
); 

// HDL Embedded Text Block 1 eb1
// HDL Embedded Text Block 2 eb2
// eb1 1             
assign xadc_rec_in=12'hB;                           
assign rst = !reset;                                     
assign irq_elink_dbg_in_active = dbg_elink;
assign debug_mode   = 1'b1;
assign dbg_spi      = 1'b1;
assign n_buses      =5'b00111;
assign miso_c = 1'b0;
assign miso_m = 1'b0;




// HDL Embedded Text Block 3 reg_assign2
// Wire_assign 1                     
  //to be changed later
initial  fifo_flush             = 1'b0;    // Upon receiving a reset message on the CANbus. FSM goes into a known state
initial  abort                  = 1'b0;
initial  time_limit             = 32'd50000000;   //corresponds to 5 sec if the FPGA freq is 40Mhz
                     






























// HDL Embedded Text Block 14 K_Code3
// Wire_assign 1                     


assign Kchar_comma = 8'hBC;//K28.5  10111100
assign Kchar_eop   = 8'hDC ;// K28.6 11011100
assign Kchar_sop   = 8'h3C ;// K28.1 00111100
assign COMMAn = 10'h305; //1100000101
assign COMMAp = 10'hFA; // 0011111010;

assign dec10b_in_dbg_uart = dec10b_in_dbg[7:0];
assign dec10b_in_rdy_sop = dec10b_in_rdy_dbg && dec10b_in_dbg == {2'b10,Kchar_sop};



























































































































endmodule // mopshub_readout
// mopshub_top_16bus_debug
