# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/dcs/git/mopshub_readout/Vivado/mopshub_readout/mopshub_readout/mopshub_readout.runs/synth_1/mopshub_readout_bd_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {Common 17-576}  -string {{WARNING: [Common 17-576] 'use_project_ipc' is deprecated. This option is deprecated and no longer used.}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'trig_out_ack' of module 'ila_v6_2_11_ila' is unconnected for instance 'inst' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'trig_out' of module 'ila_v6_2_11_ila' is unconnected for instance 'inst' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'trig_in_ack' of module 'ila_v6_2_11_ila' is unconnected for instance 'inst' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'trig_in' of module 'ila_v6_2_11_ila' is unconnected for instance 'inst' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'clkdiv_out' of module 'ila_v6_2_11_ila' is unconnected for instance 'inst' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
set_msg_config  -id {Synth 8-4446}  -string {{WARNING: [Synth 8-4446] all outputs are unconnected for this instance and logic may be removed [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/synth/mopshub_board_v3TMR.v:429]}}  -suppress 
set_msg_config  -id {Synth 8-2507}  -string {{WARNING: [Synth 8-2507] parameter declaration becomes local in debug_uart_receiverTMR with formal parameter declaration list [/home/dcs/git/mopshub/mopshub_triplicated/triple_clock_triple_reset/tmr/debug_uart_receiverTMR.v:34]}}  -suppress 
set_msg_config  -id {Synth 8-7023}  -string {{WARNING: [Synth 8-7023] instance 'proc_sys_reset_0' of module 'mopshub_board_v3TMR_proc_sys_reset_0_0' has 10 connections declared, but only 6 given [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/synth/mopshub_board_v3TMR.v:537]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'peripheral_aresetn' of module 'mopshub_board_v3TMR_proc_sys_reset_0_0' is unconnected for instance 'proc_sys_reset_0' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/synth/mopshub_board_v3TMR.v:537]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'interconnect_aresetn' of module 'mopshub_board_v3TMR_proc_sys_reset_0_0' is unconnected for instance 'proc_sys_reset_0' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/synth/mopshub_board_v3TMR.v:537]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'peripheral_reset' of module 'mopshub_board_v3TMR_proc_sys_reset_0_0' is unconnected for instance 'proc_sys_reset_0' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/synth/mopshub_board_v3TMR.v:537]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'bus_struct_reset' of module 'mopshub_board_v3TMR_proc_sys_reset_0_0' is unconnected for instance 'proc_sys_reset_0' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/synth/mopshub_board_v3TMR.v:537]}}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'clk_nobuf' of module 'ila_v6_2_11_ila' is unconnected for instance 'inst' [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
set_msg_config  -id {Synth 8-7023}  -string {{WARNING: [Synth 8-7023] instance 'inst' of module 'ila_v6_2_11_ila' has 1033 connections declared, but only 1027 given [/home/dcs/git/mopshub/Vivado/mopshub_v3TMR/mopshub_board_v3TMR/mopshub_board_v3TMR.gen/sources_1/bd/mopshub_board_v3TMR/ip/mopshub_board_v3TMR_ila_0_0/synth/mopshub_board_v3TMR_ila_0_0.v:3223]}}  -suppress 
